apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: demo
    type: svc
spec:
  ports:
  - port: 6379
    name: redis
    targetPort: 6379
  selector:
    name: redis
    app: demo
    type: pod
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis
    app: demo
    type: deployment
spec:
  selector:
    matchLabels:
      name: redis
      app: demo
      type: pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: redis
        type: pod
        app: demo
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
